language: python
# python:
#   - 3.11
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - black --check .
  - flake8 --max-line-length=100 .
  - coverage run manage.py test
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  app: mySite
  env: django-env
  bucket_name: elasticbeanstalk-us-east-2-816069163156
  on:
    repo: KarthikVV24-11-1999/mySite
    branch: main
  skip_cleanup: true